name: sql_stackexchange
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - anyio=4.6.2
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - click=8.1.7
  - expat=2.6.3
  - fastapi=0.112.2
  - h11=0.14.0
  - idna=3.7
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - psycopg2=2.9.9
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - python=3.12.7
  - readline=8.2
  - setuptools=75.1.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - uvicorn=0.20.0
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
